Init
Teaching-projects/SZE-MOSZE-2020-Git-egylet pull request #1
Opened 2020-09-18 14:35 UTC by mrpig2000

#1 feladat kész @hegyhati

2020-09-21 13:59 UTC, hegyhati requested changes

2020-09-21 13:59 UTC, hegyhati commented on functions.h
> +    void setDMG(int);
ilyenek ne legyenek. ezeket az altalanos atallitasokat nem akarjuk megengedni.

2020-09-21 13:59 UTC, hegyhati commented on functions.h
> +    bool isAlive();
const?

2020-09-21 13:59 UTC, hegyhati commented on functions.h
> +    int characterDMG;
const?

2020-09-21 13:59 UTC, hegyhati commented on game.cpp
> +}
inicializalo listaban.

2020-09-21 13:59 UTC, hegyhati commented on game.cpp
> +}
logika osztalyokban cout-ra semmikeppen ne legyen kiiratas. Ha van barmifele "kiir", akkor az altalanosan ostream-re, es preferalt, hogy akkor operatorral.

2020-09-21 13:59 UTC, hegyhati commented on game.cpp
> +
menni fog ez egy sorban is.

2020-09-21 13:59 UTC, hegyhati commented on functions.h
> +class character
character osztaly ne functions.h-ban legyen

2020-09-21 13:59 UTC, hegyhati commented on game.cpp
> +#include "functions.h"
game.cpp include-olja a functions.h-t. teljese kaosz, ne!

2020-09-21 13:59 UTC, hegyhati commented on main.cpp
> +            std::cout << argv[4] << " died. " << argv[1] << " wins." << std::endl;
na, itt mar ne hasznaljuk az argv-t

2020-09-21 13:59 UTC, hegyhati commented on main.cpp
> +    delete player1, player2;
na ezt tessek atgondolni.

2020-09-22 16:35 UTC, mrpig2000 commented
Javítva minden @hegyhati

2020-09-22 23:38 UTC, hegyhati requested changes
Ket aprosag.

2020-09-22 23:38 UTC, hegyhati commented on Character.cpp
> +void character::attack(character& target)  {
hianyolok const-ot innet is.

2020-09-22 23:38 UTC, hegyhati commented on Character.cpp
> +     return this->characterHP > 0;
:clap:

2020-09-22 23:38 UTC, hegyhati commented on main.cpp
> +int main(int argc, char* argv[]) {
ha int visszateresi ertreke van a main-nek, akkor azert illik visszaterni.

2020-09-23 09:39 UTC, destrike00 commented
Ezek is javítva @hegyhati

2020-09-23 09:42 UTC, hegyhati approved these changes

2020-09-23 09:43 UTC, merged