Documentation
Teaching-projects/SZE-MOSZE-2020-Git-egylet pull request #13
Opened 2020-11-03 20:05 UTC by mrpig2000

Elkeszult a hianyzo dokumentacio a tobbi osztalyhoz es fuggvenyhez is. 
@destrike00 kerlek add hozza reviewernek @bricsi0000000000000 -t és @fruzsin -t a PR-hoz.

2020-11-03 20:53 UTC, mrpig2000 commented
@bricsi0000000000000 es @fruzsin kerlek nezzetek at a branchet es ertekeljetek!

2020-11-03 21:22 UTC, fruzsin requested changes
Annyi észrevételem van, hogy a doxconf-ban a ,,PROJECT_NAME" és a ,,PROJECT_BRIEF" még az attackspeed-es feladathoz vannak beállítva, ezeket légyszi írd át.
Valamint a characterDMG, characterHP és a maxHP változókat írd át, mert double to int conversion miatt adatvesztési warningot dob. 
Ezen kívül részemről oké.

2020-11-03 21:57 UTC, kokohun commented
@fruzsin Javítottam a felmerülő problémákat.

2020-11-03 22:05 UTC, fruzsin approved these changes
Rendben, így jó lesz.
A conflictokat oldjátok fel még, aztán ennyi volt részemről

2020-11-03 22:20 UTC, kurucc approved these changes
Nem látok én sem semmi problémát jelenleg, kizárólag a conlictok aztán kész. :D Good job ;)

2020-11-04 03:03 UTC, mrpig2000 commented
minden javitva
@destrike00 nyomj egy approve-ot te is es megy be a masterbe

2020-11-04 03:07 UTC, kokohun approved these changes

2020-11-04 03:07 UTC, merged