Task2
Teaching-projects/SZE-MOSZE-2020-Git-egylet pull request #2
Opened 2020-09-24 18:35 UTC by mrpig2000

#2 kész @hegyhati

2020-09-26 12:59 UTC, hegyhati requested changes
Par aprosag

2020-09-26 12:59 UTC, hegyhati commented on main.cpp
> +            character player2 = character(character::parseUnit(argv[2]));
Kioptimalizalja a fordito, de azert na. Ez kicsit ... a fuggvenyben letrehozol egy uj objektumot az lemasolodik, amikor visszaadod, aztan azt atadod egy masolo konstruktornak itt megint.

2020-09-26 12:59 UTC, hegyhati commented on main.cpp
>      return 0;
Ha valami gubanc van, akkor ne terjunk 0-val vissza.

2020-09-26 12:59 UTC, hegyhati commented on task2.sh
> +done
Az indentalast tegyuk rendbe.

2020-09-27 11:37 UTC, destrike00 commented
@hegyhati  apróságok javítva

2020-09-30 08:08 UTC, mrpig2000 commented
@hegyhati

2020-09-30 08:28 UTC, hegyhati approved these changes

2020-09-30 08:29 UTC, merged