Levelup
Teaching-projects/SZE-MOSZE-2020-Git-egylet pull request #7
Opened 2020-10-15 15:17 UTC by destrike00

2020-10-17 14:23 UTC, oliverosz requested changes
Ha ezek javítva lettek, akkor frissítsd a branchet a masterre és oldd fel a conflictokat.

2020-10-17 14:23 UTC, oliverosz commented on Player.cpp
> +
És hol csökken az enemy hp-ja?

2020-10-17 14:23 UTC, oliverosz commented on Player.h
> +#include <math.h>
`<cmath>` és ide ne, csak a cpp-be

2020-10-21 14:46 UTC, oliverosz requested changes

2020-10-21 14:46 UTC, oliverosz commented on Player.cpp
> +void Player::attack(Player& enemy)
Ez így nem jó, Charactert is meg kell tudnia támadni, nem csak másik Playert.

2020-10-21 14:46 UTC, oliverosz commented on main.cpp
> +            Character player2 = Player::parseUnit(argv[2]);
Ez így nem lesz jó, a visszaadott Playert Characterré konvertálja.

2020-10-22 11:14 UTC, destrike00 commented
@oliverosz javítottam, így már lefut a levelup logika

2020-10-22 11:31 UTC, oliverosz approved these changes

2020-10-22 11:31 UTC, merged

2020-10-22 12:00 UTC, destrike00 commented
@oliverosz  Félreértés: Még nem frissítettem a branchet, így a master mögött van. Megtennéd, hogy restoreolod? 
Bocsi a kellemetlenségért, először a logikát akartam rendben tudni.

2020-10-22 12:10 UTC, destrike00 commented
@oliverosz  Köszi! A masterből is tudjuk törölni az előző commitokat? Így még bennemaradtak ha jól látom.

2020-10-22 12:10 UTC, oliverosz commented
@destrike00 Hmm, valóban nem jól lett egyesítve. Csak láttam a merge commitot, meg nem volt conflict, de alaposabban nem néztem meg. A branchet restore-oltam, de azt hiszem új PR-t kell majd nyitni az új commitokból.

2020-10-22 12:12 UTC, oliverosz commented
> @oliverosz Köszi! A masterből is tudjuk törölni az előző commitokat? Így még bennemaradtak ha jól látom.

A master már így marad, új commitokként kell majd hozzáfűzni a javításokat.